// Copyright © 2026, Oracle and/or its affiliates. All rights reserved.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

group = 'com.pushio.manager.flutter'
version = '7.1.6'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:9.0.1'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

dependencies {
    compileOnly 'com.google.firebase:firebase-messaging:25.0.1'
    implementation project(":PushIOManager")
    implementation "androidx.work:work-runtime:2.11.2"
    implementation 'androidx.annotation:annotation:1.9.1'
    implementation 'androidx.security:security-crypto:1.1.0'
    implementation 'net.zetetic:sqlcipher-android:4.14.1'
    implementation 'androidx.sqlite:sqlite:2.6.2'
    implementation 'androidx.room:room-runtime:2.8.4'
}

android {

    namespace = 'com.pushio.manager.flutter'

    compileSdk = 36

    defaultConfig {
        minSdk = 24
        targetSdk = 35
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}
